### PR TITLE
newest redis

### PR DESCRIPTION
**Pull request by cigolpl**

### CODE REVIEW

**Comment by pilot** [comment]
@cigolpl where is redis used? there is nothing in the doc about it ;)

**Comment by cigolpl** [comment]
@pilot it is used in the newest pretty url feature.

Before when you wanted to filter items by some options you could do:

``js
client.search({
  key: 'actors',
  val: 'Brad Pitt',
})
``
but url was very ugly then `filter/actors/Tom%20Hanks`

and now with redis feature
``js
client.search({
  key: 'actors',
  val: 'brad-pitt',
})
``
url looks awesome and seo friendly like `filter/actors/tom-hanks`

This feature is optional - only if you provide specific options in config which fields you want to make looking nice:
``js
slugs: ["actors", "tags"]
``

Redis probably should be optional too but need to test if it is still optional.
Good point with docs - will add that!

**Comment by cigolpl** [comment]
@pilot, @pjedrzejewski I am wondering if I should make redis optional at all.
Of course it is better when it is optional but it would require more cases and exceptions to cover. On the other hand redis is very lightweight and easy to install (usually `sudo apt-get install redis-server`) and could be useful for some other features in the future i.e. caching or authentication.

Your advice will be appreciated

**Comment by pilot** [comment]
@cigolpl redis not sure that there is good point to increase the minimum requirements stack, better to have it optional at least on current moment, but in other hand as you say it's easy for maintaining make a required by default then this is make a sense for me. 

Be cause you going father faster without to take care about to support redis, non-redis versions

btw. can you show please what definitely redis do for better slag, I really like that slag's will looks good :), but seems that redis not the right tool to do this or maybe I'm wrong.

**Comment by cigolpl** [comment]
@pilot thank you for comment. You are right. That sounds very reasonable though to keep redis optional and stack minimum as possible i.e. because demo installation on heroku will be simplier.

What redis does for slugs is keeping values for specific keys i.e.
`"movie_actors_brad-pitt" -> "Brad Pitt"`
`"movie_genres_drama" -> "Drama"`
 
They are generated automatically out of the box. I was thinking on another solution even with mongodb or elasticsearch analyzers but redis as key value datastore seems for me to be the simplest and blazingly fast solution.
If you have better idea to do that feature just please let me know

**Pull request merged**
