### PR TITLE
Create circle.yml

### PR DESCRIPTION
**Pull request by cigolpl**

### CODE REVIEW

**Comment by pilot** [comment]
+1

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by cigolpl** [comment]
There was a problem with elasticsearch but working now - #65. Glad you like that :)

**Comment by pjedrzejewski** [comment]
Offtopic - Funny to run into friends on new Open Source projects. Hope we can have a beer in 2016 @pilot :)

**Comment by cigolpl** [comment]
:+1: ;)

**Comment by pilot** [comment]
yeah :)

**Pull request merged**
